# Generated by Django 4.0.6 on 2022-07-29 20:45

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplefile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleFileCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/simplestorage'), upload_to='uploads/', verbose_name='File')),
            ],
            options={
                'db_table': 'simple_file_custom',
            },
        ),
    ]
