# Generated by Django 4.0.6 on 2022-07-30 03:16

import django.core.files.storage
from django.db import migrations, models
import simplefile.validators


class Migration(migrations.Migration):

    dependencies = [
        ('simplefile', '0002_simplefilecustom'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleUploadValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/tiago/www-storage/'), upload_to='uploads/', validators=[simplefile.validators.validate_file_extension], verbose_name='File')),
            ],
            options={
                'db_table': 'simple_file_validation',
            },
        ),
        migrations.AlterField(
            model_name='simplefilecustom',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/tiago/www-storage/'), upload_to='uploads/', verbose_name='File'),
        ),
    ]
