# Generated by Django 4.0.6 on 2022-07-31 16:32

import django.core.files.storage
from django.db import migrations, models
import simplefile.validators


class Migration(migrations.Migration):

    dependencies = [
        ('simplefile', '0003_simpleuploadvalidation_alter_simplefilecustom_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleFileDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/tiago/www-storage/'), upload_to='uploads/', validators=[simplefile.validators.validate_file_extension], verbose_name='File')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('hash_name', models.CharField(max_length=255, verbose_name='Hash name')),
                ('extension', models.CharField(max_length=10, verbose_name='Extension')),
                ('size', models.IntegerField(verbose_name='Size')),
                ('content_type', models.CharField(max_length=100, verbose_name='Content Type')),
            ],
            options={
                'db_table': 'simple_file_detail',
            },
        ),
    ]
