# Generated by Django 4.0.6 on 2022-07-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplefile', '0004_simplefiledetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplefiledetails',
            name='uuid',
            field=models.UUIDField(default='52f09db681ae42f5a100fe6073b05918', verbose_name='Identifier'),
        ),
    ]
