# Generated by Django 4.0.6 on 2022-07-31 17:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('simplefile', '0005_simplefiledetails_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simplefiledetails',
            name='uuid',
        ),
        migrations.AddField(
            model_name='simplefiledetails',
            name='identifier',
            field=models.UUIDField(default=uuid.UUID('c0f9bd65-cdc4-495b-aa8a-08cf1333aded'), verbose_name='Identifier'),
        ),
    ]
