# Generated by Django 4.0.6 on 2022-08-01 03:09

import django.core.files.storage
from django.db import migrations, models
import simplefile.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('simplefile', '0007_simplefiledetails_full_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleFileId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('identifier', models.UUIDField(default=uuid.UUID('795e5fb2-20c3-4716-b00a-4d97db90960d'), verbose_name='Identifier')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/tiago/www-storage/'), upload_to='uploads/', validators=[simplefile.validators.validate_file_extension], verbose_name='File')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('hash_name', models.CharField(max_length=255, verbose_name='Hash name')),
                ('extension', models.CharField(max_length=10, verbose_name='Extension')),
                ('size', models.IntegerField(verbose_name='Size')),
                ('content_type', models.CharField(max_length=100, verbose_name='Content Type')),
                ('full_path', models.CharField(blank=True, max_length=255, verbose_name='Full Path')),
            ],
            options={
                'db_table': 'simple_file_id',
            },
        ),
        migrations.AlterField(
            model_name='simplefiledetails',
            name='identifier',
            field=models.UUIDField(default=uuid.UUID('5f02f499-65b0-4b64-a038-cbaa10f79a9f'), verbose_name='Identifier'),
        ),
    ]
